[package]
name = "file_explorer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "file_explorer"
path = "src/main.rs"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
ui.workspace = true
file_icons.workspace = true
lazy_static.workspace = true
dirs.workspace = true
